### ISSUE TITLE
No reconoce codigos de ubicacion si tiene espacios

### ISSUE THREAD

**Issue by dboterov** [dboterov/igb-java#6]
Si al ingresar un codigo de ubicacion se ingresan espacios al ppio o al final, no se reconoce el codigo de la ubicacion

**Comment by yeijara94** [comment]
![resupply - location](https://user-images.githubusercontent.com/30330091/40271867-660c4c4c-5b69-11e8-8c23-3eac74977fda.PNG)

Se probo en re abastecimiento con espacios en la ubicación y realizo los traslado con éxito.

![picking - location](https://user-images.githubusercontent.com/30330091/40271919-0ef52f18-5b6a-11e8-993f-8eb615251b1b.PNG)

También se prueba en el modulo de picking, dando éxito también este.

![inventory - location](https://user-images.githubusercontent.com/30330091/40272193-6667cd28-5b6f-11e8-85f8-6c8295dc4b56.PNG)

Se valida en inventory funcionando también.
